#!/usr/bin/env python3
"""Draws the Google Play Games achievement icons: one 512x512 PNG per achievement
(src/f1/achievements.ts), a pixel-art symbol on a dark badge in a gold ring, in
the game's colours. Play greys an icon out itself while it's locked.

    python3 tools/achievement-art.py        (needs Pillow: pip install pillow)

Writes store/achievements/<id>.png.
"""
from pathlib import Path

from PIL import Image, ImageDraw

OUT = Path(__file__).resolve().parent.parent / 'store/achievements'
N = 64  # the pixel grid; scaled up 8x, crisp
DECK = (14, 13, 22)
INNER = (34, 32, 56)
RING = (242, 193, 78)
RING_SHADE = (176, 128, 36)
C = {
    'W': (244, 244, 248), 'R': (216, 50, 60), 'r': (150, 28, 38), 'G': (242, 193, 78), 'g': (196, 140, 40),
    'K': (24, 24, 30), 'S': (150, 152, 170), 's': (96, 98, 116), 'B': (70, 150, 240), 'b': (40, 90, 170),
    'P': (176, 92, 255), 'O': (255, 150, 50), 'Y': (255, 230, 90), 'C': (63, 240, 255), 'E': (92, 200, 110),
    'e': (50, 130, 70), 'T': (120, 80, 50),
}

# each symbol 16x16, drawn at 2x in the badge's middle
ART = {
    'finish': """
.S..............
.SWWKKWWKKWW....
.SWWKKWWKKWW....
.SKKWWKKWWKK....
.SKKWWKKWWKK....
.SWWKKWWKKWW....
.SWWKKWWKKWW....
.SKKWWKKWWKK....
.SKKWWKKWWKK....
.S..............
.S..............
.S..............
.S..............
.S..............
SSS.............
................""",
    'podium': """
................
.......GG.......
......GGGG......
.......GG.......
................
......WWWW......
......W11W......
..SS..W11W......
.SSSS.WWWW..OO..
..SS.WWWWWW.OO..
.WWWWWWWWWWWWWW.
.W22WWWWWWWW33W.
.W22WWWWWWWW33W.
.WWWWWWWWWWWWWW.
.WWWWWWWWWWWWWW.
................""",
    'win': """
................
...GGGGGGGGGG...
.GGGGGGGGGGGGGG.
.G.GGGGGGGGGG.G.
.G.GGGGWGGGGG.G.
..GGGGGWGGGGGG..
....GGGGGGGG....
.....GGGGGG.....
......gGGg......
.......GG.......
.......GG.......
......gGGg......
....GGGGGGGG....
....KKKKKKKK....
....GGGGGGGG....
................""",
    'hard-win': """
................
................
..G....G....G...
..GG..GGG..GG...
..GGG.GGG.GGG...
..GGGGGGGGGGG...
..GGRGGGGGRGG...
..GGGGGBGGGGG...
..GGGGGGGGGGG...
..ggggggggggg...
..GGGGGGGGGGG...
................
................
................
................
................""",
    'wet-win': """
................
......WWWW......
....WWWWWWWW....
...WWWWWWWWWW...
.WWWWWWWWWWWWWW.
WWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWW
.SSSSSSSSSSSSSS.
................
..B...B...B...B.
..B...B...B...B.
.B...B...B...B..
.B...B...B...B..
B...B...B...B...
B...B...B...B...
................""",
    'from-back': """
.......GG.......
......GGGG......
.....GGGGGG.....
....GGGGGGGG....
...GGGGGGGGGG...
..GGGGGGGGGGGG..
......GGGG......
......GGGG......
......GGGG......
......GGGG......
......GGGG......
......GGGG......
................
..S.S.S.S.S.S...
..S.S.S.S.S.S...
................""",
    'charge': """
................
................
.GG......GG.....
.GGG.....GGG....
..GGG.....GGG...
...GGG.....GGG..
....GGG.....GGG.
.....GGG.....GGG
.....GGG.....GGG
....GGG.....GGG.
...GGG.....GGG..
..GGG.....GGG...
.GGG.....GGG....
.GG......GG.....
................
................""",
    'hat-trick': """
................
.....KKKKKK.....
.....KKKKKK.....
.....KKKKKK.....
.....KKKKKK.....
.....KKKKKK.....
.....KKKKKK.....
.....RRRRRR.....
.....KKKKKK.....
..KKKKKKKKKKKK..
.KKKKKKKKKKKKKK.
................
...G...G...G....
..GGG.GGG.GGG...
...G...G...G....
................""",
    'spotless': """
.......C........
.......C........
......CWC.......
......CWC.......
.....CWWWC......
..CCCWWWWWCCC...
CCWWWWWWWWWWWCC.
..CCCWWWWWCCC...
.....CWWWC......
......CWC.......
......CWC.......
.......C........
.......C......C.
.............CWC
..............C.
................""",
    'purple': """
......PPPP......
.......PP.......
.....PPPPPP.....
...PPWWWWWWPP...
..PWWWWWWWWWWP..
..PWWWWKWWWWWP..
.PWWWWWKWWWWWWP.
.PWWWWWKWWWWWWP.
.PWWWWWKKKKWWWP.
.PWWWWWWWWWWWWP.
..PWWWWWWWWWWP..
..PWWWWWWWWWWP..
...PPWWWWWWPP...
.....PPPPPP.....
................
................""",
    'endurance': """
..GGGGGGGGGGGG..
..GGGGGGGGGGGG..
...W........W...
...WYYYYYYYYW...
....WYYYYYYW....
.....WYYYYW.....
......WYYW......
.......WW.......
......W..W......
.....W....W.....
....W..YY..W....
...W..YYYY..W...
...WYYYYYYYYW...
..GGGGGGGGGGGG..
..GGGGGGGGGGGG..
................""",
    'bald': """
................
.....KKKKKK.....
...KKKKKKKKKK...
..KKKSSSSSSKKK..
.KKSSKKKKKKSSKK.
.KKSKKSSSSKKSKK.
KKSKKSSSSSSKKSKK
KKSKKSS..SSKKSKK
KKSKKSS..SSKKSKK
KKSKKSSSSSSKKSKK
.KKSKKSSSSKKSKK.
.KKSSKKKKKKSSKK.
..KKKSSSSSSKKK..
...KKKKKKKKKK...
.....KKKKKK.....
................""",
    'torch': """
.......R........
......RR........
......RRR.......
.....RRRR...R...
.....RROR..RR...
....RRROOR.RR...
...RRROOOORRR...
...RROOOOORRR...
..RROOYYOOORRR..
..RROOYYYOOORR..
..RROYYYYYOORR..
..RROYYWYYYORR..
...RROYWWYYORR..
...RROOYYYOORR..
....RRROOOORR...
......RRRRR.....""",
    'rocket': """
...........WW...
..........WWWW..
.........WWWRW..
........WWWRRW..
.......WWWWWW...
......WWWWWW....
...SSWWWWWW.....
..SSSWWWWW......
.....SWWWS......
....OSWWSS......
...OOSSS.SS.....
..OYO.S...S.....
..YO............
.Y..............
................
................""",
    'too-keen': """
................
....KKKKKKKK....
....KRRKKRRK....
....KRRKKRRK....
....KKKKKKKK....
....KRRKKRRK....
....KRRKKRRK....
....KKKKKKKK....
....KRRKKRRK....
....KRRKKRRK....
....KKKKKKKK....
.......SS.......
.......SS.......
.......SS.......
......SSSS......
................""",
    'torpedo': """
................
.......Y........
.Y.....Y.....Y..
..Y...YOY...Y...
...Y.YOOOY.Y....
....YOOROOY.....
..YYOORRROOYY...
YYOOORRWRROOOYY.
..YYOORRROOYY...
....YOOROOY.....
...Y.YOOOY.Y....
..Y...YOY...Y...
.Y.....Y.....Y..
.......Y........
................
................""",
    'box': """
................
..SSS...........
.SS.SS..........
.S...S..........
.SS..SS.........
..SSSSSS........
.....SSSS.......
......SSSS......
.......SSSS.....
........SSSS....
.........SSSSS..
..........SS.SS.
..........S...S.
...........SS.S.
............SSS.
................""",
    'no-stop': """
................
................
.GG.....GG......
.GGGG...GGGG....
.GGGGGG.GGGGGG..
.GGGGGGGGGGGGGG.
.GGGGGGGGGGGGGGG
.GGGGGGGGGGGGGGG
.GGGGGGGGGGGGGG.
.GGGGGG.GGGGGG..
.GGGG...GGGG....
.GG.....GG......
................
................
................
................""",
    'lapped': """
................
.....GGGGGG.....
...GGGGGGGGGG...
..GGG......GGG..
.GGG........GG..
.GG.........GGG.
.GG........GGGGG
.GG.........GGG.
.GG..........G..
.GG.............
.GGG.......G....
..GGG.....GG....
...GGGGGGGGGGG..
.....GGGGGGG....
...........G....
................""",
    'scrapheap': """
................
......SSSS......
..SS..SSSS..SS..
..SSSSSSSSSSSS..
...SSSSSSSSSS...
...SSS....SSS...
.SSSS......SSSS.
.SSS........SSS.
.SSS........SSS.
.SSSS......SSSS.
...SSS....SSS...
...SSSSSSSSSS...
..SSSSSSSSSSSS..
..SS..SSSS..SS..
......SSSS......
................""",
    'golden': """
..RR........BB..
...RR......BB...
....RR....BB....
.....RR..BB.....
......RRBB......
.......RB.......
.....GGGGGG.....
...GGGGGGGGGG...
...GGggggggGG...
..GGgGGGGGGgGG..
..GGgGGWGGGgGG..
..GGgGGWGGGgGG..
..GGgGGGGGGgGG..
...GGggggggGG...
...GGGGGGGGGG...
.....GGGGGG.....""",
    'gold-standard': """
................
.......G........
......GGG.......
......GGG.......
.GGGGGGGGGGGGG..
..GGGGGGGGGGG...
...GGGGGGGGG....
....GGGGGGG.....
....GGGGGGG.....
...GGGG.GGGG....
...GGG...GGG....
..GG.......GG...
................
..W.W.W.W.W.W...
................
................""",
    'champion': """
..E..........E..
.Ee..GGGGGG..eE.
.E..GGGGGGGG..E.
Ee..GG.GG.GG..eE
E...GG.GG.GG...E
E...GGGGGGGG...E
Ee...GGGGGG...eE
.E....GGGG....E.
.Ee....GG....eE.
..E....GG....E..
..Ee..GGGG..eE..
...E.GGGGGG.E...
....EKKKKKKE....
.....GGGGGG.....
................
................""",
    'globetrotter': """
................
.....BBBBBB.....
...BBEEBBBBBB...
..BBEEEEBBEEBB..
..BEEEEBBBEEEB..
.BBBEEEBBBBEEBB.
.BBBBEBBBBBBEBB.
.BBBBBBBEEBBBBB.
.BBBBBBEEEEBBBB.
.BBBBBBBEEEEBBB.
..BBBBBBBEEBBB..
..BBEBBBBBBBBB..
...BBEEBBBBBB...
.....BBBBBB.....
................
................""",
    'regular': """
..R..........R..
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.WWWWWWWWWWWWWW.
.WWWWWWWWWWWWWW.
.WWWWKKKKKKWWWW.
.WWWWWWWWWKKWWW.
.WWWWWWWWKKWWWW.
.WWWWWWWKKWWWWW.
.WWWWWWKKWWWWWW.
.WWWWWKKWWWWWWW.
.WWWWWKKWWWWWWW.
.WWWWWWWWWWWWWW.
.SSSSSSSSSSSSSS.
................
................""",
    'devoted': """
.......R........
......RR........
......RRR.......
.....RRRR...R...
....RROORR..RR..
....RROOORR.RR..
...RROOOOORRRR..
...RROOYOOORRR..
..RROOYYYOOORR..
..RROOYYYYOORR..
..RROOYYYYYOORR.
..RROOYYWYYOORR.
...RROOYWWYOORR.
...RRROOYYOORR..
....RRROOOORR...
......RRRRRR....""",
    'busy-day': """
.....SSSSSS.....
..TTTSKKKKSTTT..
..TWWWWWWWWWWT..
..TWWWWWEWWWWT..
..TWEWWEWWSSWT..
..TWWEEWWWWWWT..
..TWWWWWWWWWWT..
..TWWWWWEWWWWT..
..TWEWWEWWSSWT..
..TWWEEWWWWWWT..
..TWWWWWWWWWWT..
..TWWWWWEWWWWT..
..TWEWWEWWSSWT..
..TWWEEWWWWWWT..
..TTTTTTTTTTTT..
................""",
}
# the podium's step numbers are drawn in, not part of the palette
DIGITS = {'1': 'K', '2': 'K', '3': 'K'}


def badge(sym: str) -> Image.Image:
    im = Image.new('RGBA', (N, N), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    d.ellipse((1, 1, N - 2, N - 2), fill=RING_SHADE)
    d.ellipse((1, 0, N - 2, N - 3), fill=RING)
    d.ellipse((6, 6, N - 7, N - 7), fill=DECK)
    d.ellipse((7, 7, N - 8, N - 8), fill=INNER)
    rows = [r for r in sym.strip('\n').split('\n')]
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), rows
    # (centred on the symbol's own bounds, so each sits in the middle of its badge)
    cells = [(x, y) for y, row in enumerate(rows) for x, ch in enumerate(row) if ch != '.']
    x0, x1 = min(x for x, _ in cells), max(x for x, _ in cells)
    y0, y1 = min(y for _, y in cells), max(y for _, y in cells)
    ox = (N - 2 * (x1 - x0 + 1)) // 2 - 2 * x0
    oy = (N - 2 * (y1 - y0 + 1)) // 2 - 2 * y0
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            ch = DIGITS.get(ch, ch)
            if ch == '.':
                continue
            d.rectangle((ox + 2 * x, oy + 2 * y, ox + 2 * x + 1, oy + 2 * y + 1), fill=C[ch])
    return im.resize((512, 512), Image.NEAREST)


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    for k, sym in ART.items():
        # (on the deck's colour: Play wants no transparency)
        bg = Image.new('RGB', (512, 512), DECK)
        b = badge(sym)
        bg.paste(b, (0, 0), b)
        bg.save(OUT / f'{k}.png')
    print(len(ART), 'icons in', OUT)
